CREATE TABLE RAW.COINMARKETCAP (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	RANK INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	SYMBOL VARCHAR(50) NOT NULL,
	MARKETCAP VARCHAR(255) NOT NULL,
	PRICE VARCHAR(255) NOT NULL,
	CIRCULATINGSUPPLY VARCHAR(255) NOT NULL,
	VOLUME VARCHAR(255) NOT NULL,
	PERCENTPERHOUR VARCHAR(50) NOT NULL,
	PERCENTPERWEEK VARCHAR(50) NOT NULL,
	PERCENTPERDAY VARCHAR(50) NOT NULL,
	FILEDATE DATETIME,
	CREATEDAT DATETIME
);