CREATE TABLE DIM.COINS (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	RANK INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	SYMBOL VARCHAR(50),
	TYPEID INT FOREIGN KEY REFERENCES DIM.TYPES(ID),
	CATEGORYID INT FOREIGN KEY REFERENCES DIM.CATEGORIES(ID),
	IMAGES VARCHAR(255),
	CREATEDAT DATETIME NOT NULL,
	UPDATEDAT DATETIME
  );