CREATE OR REPLACE PROCEDURE WH_CRYPTO.DBO.MERGECATEGORYFROMRAWTABLE()
RETURNS VARCHAR
EXECUTE AS OWNER
AS
$$
BEGIN
MERGE INTO WH_CRYPTO.DIM.CATEGORIES AS TGT
USING (SELECT DISTINCT CATEGORY FROM WH_CRYPTO.RAW.COINRANKING WHERE CATEGORY IS NOT NULL) AS SRC
ON TGT.CATEGORY = SRC.CATEGORY
WHEN NOT MATCHED THEN
	INSERT (CATEGORY, CREATEDAT)
	VALUES (SRC.CATEGORY, GETDATE());
RETURN 'Data Loaded Successfully';
END;
$$;
