CREATE OR REPLACE PROCEDURE WH_CRYPTO.DBO.USP_MERGECOINSFROMRAWTABLE()
RETURNS VARCHAR
EXECUTE AS OWNER
AS
$$
BEGIN
MERGE INTO WH_CRYPTO.DIM.COINS AS TGT
USING (SELECT DISTINCT CM.NAME,
			CM.SYMBOL,
			T.ID AS TYPEID,
			C.ID AS CATEGORYID,
			CM.IMAGE
	   FROM WH_CRYPTO.RAW.COINRANKING CM
			JOIN WH_CRYPTO.DIM.TYPES T ON CM.TYPE = T.TYPE
			JOIN WH_CRYPTO.DIM.CATEGORIES C ON CM.CATEGORY = C.CATEGORY
	   ) AS SRC
ON TGT.NAME = SRC.NAME AND TGT.SYMBOL = SRC.SYMBOL
WHEN NOT MATCHED THEN
	INSERT (NAME, SYMBOL, TYPEID, CATEGORYID, IMAGES, CREATEDAT)
	VALUES (SRC.NAME, SRC.SYMBOL, SRC.TYPEID, SRC.CATEGORYID, SRC.IMAGE, GETDATE())
WHEN MATCHED AND (TGT.TYPEID <> SRC.TYPEID OR TGT.CATEGORYID <> SRC.CATEGORYID)  THEN UPDATE SET
	TGT.TYPEID = SRC.TYPEID,
	TGT.CATEGORYID = SRC.CATEGORYID,
	TGT.UPDATEDAT = GETDATE();
RETURN 'Data loaded successfully';
END;
$$;